export const GET_PASSWORD_EVENT = 'get.password.event'
export const SAVE_PASSWORD_EVENT = 'save.password.event'
export const VERIFY_PASSWORD_EVENT = 'verify.password.event'
export const GET_NETWORKS_EVENT = 'get.networks.event'
export const SAVE_NETWORKS_EVENT = 'save.networks.event'
export const DELETE_NETWORKS_EVENT = 'delete.networks.event'